[package]
name = "longest-harmonious-subsequence"
version = "0.1.0"
authors = ["Suguru Motegi <suguru.motegi@gmail.com>"]
edition = "2018"

[dependencies]

[lib]
name = "longest_harmonious_subsequence"
path = "solution.rs"
