[package]
name = "minimum-remove-to-make-valid-parentheses"
version = "0.1.0"
authors = ["Suguru Motegi <suguru.motegi@gmail.com>"]
edition = "2018"

[dependencies]

[lib]
name = "minimum_remove_to_make_valid_parentheses"
path = "solution.rs"
