[package]
name = "score-of-parentheses"
version = "0.1.0"
authors = ["Suguru Motegi <suguru.motegi@gmail.com>"]
edition = "2018"

[dependencies]

[lib]
name = "score_of_parentheses"
path = "solution.rs"
