[package]
name = "the-k-weakest-rows-in-a-matrix"
version = "0.1.0"
authors = ["Suguru Motegi <suguru.motegi@gmail.com>"]
edition = "2018"

[dependencies]

[lib]
name = "the_k_weakest_rows_in_a_matrix"
path = "solution.rs"
