[package]
name = "path-with-minimum-effort"
version = "0.1.0"
authors = ["Suguru Motegi <suguru.motegi@gmail.com>"]
edition = "2018"

[dependencies]

[lib]
name = "path_with_minimum_effort"
path = "solution.rs"
