[package]
name = "check-if-two-string-arrays-are-equivalent"
version = "0.1.0"
authors = ["Suguru Motegi <suguru.motegi@gmail.com>"]
edition = "2018"

[dependencies]

[lib]
name = "check_if_two_string_arrays_are_equivalent"
path = "solution.rs"
