[package]
name = "longest-word-in-dictionary-through-deleting"
version = "0.1.0"
authors = ["Suguru Motegi <suguru.motegi@gmail.com>"]
edition = "2018"

[dependencies]

[lib]
name = "longest_word_in_dictionary_through_deleting"
path = "solution.rs"
