[package]
name = "longest-palindromic-substring"
version = "0.1.0"
authors = ["Suguru Motegi <suguru.motegi@gmail.com>"]
edition = "2018"

[dependencies]

[lib]
name = "longest_palindromic_substring"
path = "solution.rs"
