[package]
name = "container-with-most-water"
version = "0.1.0"
authors = ["Suguru Motegi <suguru.motegi@gmail.com>"]
edition = "2018"

[dependencies]

[lib]
name = "container_with_most_water"
path = "solution.rs"
