[package]
name = "create-sorted-array-through-instructions"
version = "0.1.0"
authors = ["Suguru Motegi <suguru.motegi@gmail.com>"]
edition = "2018"

[dependencies]

[lib]
name = "create_sorted_array_through_instructions"
path = "solution.rs"
