[package]
name = "search-insert-position"
version = "0.1.0"
authors = ["Suguru Motegi <suguru.motegi@gmail.com>"]
edition = "2018"

[dependencies]

[lib]
name = "search_insert_position"
path = "solution.rs"
