[package]
name = "shortest-unsorted-continuous-subarray"
version = "0.1.0"
authors = ["Suguru Motegi <suguru.motegi@gmail.com>"]
edition = "2018"

[dependencies]

[lib]
name = "shortest_unsorted_continuous_subarray"
path = "solution.rs"
