[package]
name = "shortest-path-in-binary-matrix"
version = "0.1.0"
authors = ["Suguru Motegi <suguru.motegi@gmail.com>"]
edition = "2018"

[dependencies]

[lib]
name = "shortest_path_in_binary_matrix"
path = "solution.rs"
